services:
  new_db:
    build:
      context: . 
    container_name: new_db  
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase 
    ports:
      - "5432:5432"

    networks:
      - my_network

networks:
  my_network:
    driver: bridge
